definitions:
  synapse_config: "/home/bgrande/repos/imcore_data_model/.synapseConfig"
  creds_path: "/home/bgrande/repos/imcore_data_model/credentials.json"
  token_pickle: "/home/bgrande/repos/imcore_data_model/token.pickle"
  service_acct_creds: "/home/bgrande/repos/imcore_data_model/schematic_service_account_creds.json"

synapse:
  master_fileview: "syn23512327"
  manifest_folder: "manifests"
  manifest_filename: "manifest.csv"
  token_creds: "syn23643259"
  service_acct_creds: "syn25171627"

manifest:
  title: "Patient Manifest"
  data_type: "Patient"

model:
  input:
    location: "/home/bgrande/repos/imcore_data_model/imcore.model.jsonld"
    file_type: "local"

style:
  google_manifest:
    req_bg_color:
      red: 0.9215
      green: 0.9725
      blue: 0.9803
    opt_bg_color:
      red: 1.0
      green: 1.0
      blue: 0.9019
    master_template_id: "1LYS5qE4nV9jzcYw5sXwCza25slDfRA1CIg3cs-hCdpU"
